# Generated by Django 4.0.6 on 2022-08-05 04:09

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Itinerary',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('coint', models.CharField(max_length=16)),
                ('agent', models.CharField(max_length=32)),
                ('agent_rating', models.DecimalField(decimal_places=1, max_digits=6)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
