# Generated by Django 4.0.6 on 2022-08-06 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itineraries', '0002_itinerarylegs_itinerary_legs_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itinerary',
            old_name='coint',
            new_name='currency',
        ),
    ]
