site_name: flights
site_description: Flights a round the world
repo_url: https://github.com/puroh/flights-django
site_dir: site
copyright: Copyright &copy; 2020, <a href="https://github.com/puroh">puroh</a>.
dev_addr: 0.0.0.0:8001

nav:
  - Home: "index.md"
  - API:
      - Authentication: "api/authentication.md"
      - Users: "api/users.md"
      - Legs: "api/leg.md"
      - Itineraries: "api/itinerary.md"
      - Itineraries-legs: "api/itinerary-leg.md"
