# Generated by Django 4.0.6 on 2022-08-05 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leg',
            name='airline_id',
            field=models.CharField(max_length=32),
        ),
    ]
